FROM nvcr.io/nvidia/pytorch:25.08-py3

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     libopencv-dev python3-opencv && \
#     rm -rf /var/lib/apt/lists/*

COPY perception/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /workspace/perception

CMD ["bash"]